### PR TITLE
Updated for django 1.10 and Python3

### PR DESCRIPTION
**Pull request by rmad17**
I updated the code to add support for python3 and made changes to work with django 1.10 as well. Tested with python 2.

### CODE REVIEW

**Comment by ryan-roemer** [comment]
Thanks for the update! Can you

- [ ] Fix CI for the pylint failure?
- [ ] Add a "good" python3 version to `"2.7"` so we run both in Travis CI?

Thanks!

**Comment by rmad17** [comment]
Hey @ryan-roemer . I removed two unused variables. Now PyLint is warning about a builtin called filter. I did some searching and most people recommend  ignoring the warning. Can you tell me what I need to do to fix the linting error.
Also what did you mean by ` Add a "good" python3 version to "2.7" so we run both in Travis CI?` Sorry I did not understand.

**Comment by ryan-roemer** [comment]
@rmad17 -- Not sure about `filter`. You can ignore it if you also provide an online link to it being spurious.

For travis, I mean switch this:

```yaml
python:
  - "2.7"
```

to add a python3 version that is a good one to test (I don't use py3 right now), so:

```yaml
python:
  - "2.7"
  - "3.PICK_A_VERSION_HERE"
```

**Comment by aidanrussell** [comment]
Can this be fixed? Currently package not compatible with Python 3. For a version then 3.6 is the latest.

**Comment by ryan-roemer** [comment]
@aidanrussell -- If you can open a new PR using @aidanrussell 's fine work as a start and my comment guidance to get CI passing for both Python 2 and 3, I'll merge and release. Thanks!

**Comment by ryan-roemer** [comment]
Superseded by #14

**Pull request closed without merging**
