### PR TITLE
Python 3 + Django 2.0 support

### PR DESCRIPTION
**Pull request by corcoran**

### CODE REVIEW

**Comment by ryan-roemer** [comment]
Thanks for the PR! It looks like CI is failing for requirements -- could you potentially take a look at what's up and upgrade things appropriately? Thanks!

**Comment by corcoran** [comment]
The issue originally stemmed from boto + travis but it had nothing to do with my code and just required a workaround.

I've added a proper python 3 travis check and fixed up a few more things.

**Comment by ryan-roemer** [comment]
Tremendous work @corcoran !

Changes released in https://pypi.python.org/pypi/django-cloud-browser/0.4.0

As this lib is a bit behind the times, I've filed issues to:

- Deprecate `cloudfiles` and replace with `swiftclient`. #16 
- Replace `pep8` (now removed) and replace with `pycodestyle`. #15

**Comment by corcoran** [comment]
Issue #16 is addressed in this PR btw

**Comment by ryan-roemer** [comment]
@corcoran -- I saw the `requirements_dev.txt` change, but all the files presupposes an `import cloudfiles` which I believe is now broken everywhere, so I think we need a big ol' refactoring of:

1. The code to new `swiftclient`, and
2. Changing text / docs of `Rackspace` to `OpenStack`

... or is everything much simpler than I'm imagining here? 😄

**Comment by corcoran** [comment]
No you're definitely right, my bad!

I don't have any rackspace accounts myself to help test/refactor
unfortunately

**Pull request merged**
