### PR TITLE
Fix install on Python >= 3.6

### PR DESCRIPTION
**Pull request by c-w**
As discussed in https://github.com/ryan-roemer/django-cloud-browser/issues/17, the package currently doesn't install on Python versions 3.6 or newer due to the distribute install dependency. For example, see below for a screenshot showing a failed install on Python 3.6.5:

Screenshot showing install failure on Python 3.6

This pull request removes the distribute dependency when installing on Python >= 3.6 which makes the package install cleanly.

Resolves https://github.com/ryan-roemer/django-cloud-browser/issues/17

### CODE REVIEW

**Comment by ryan-roemer** [comment]
Fantastic work on this and the other PRs you've opened! I'll get everything reviewed, merged, and released next week when I have a moment to get my head back into this lib + Python again 😄

**Comment by c-w** [comment]
Thanks and looking forward to your reviews!

**Comment by ryan-roemer** [comment]
@c-w -- I've been digging into this, but I confess that I'm having difficulties getting back into this project with a modern python. Here's my current env:

```sh
$ python --version
Python 3.7.2
$ cat requirements_dev.txt 
Django>=1.8.0
Fabric3==1.14.post1
boto==2.48.0
pylint==2.3.1
python-swiftclient==3.5.0
Sphinx==1.6.1
sphinx-bootstrap-theme>=0.7.1
```

I'm attempting to run:

```sh
# Check lint, which fails presumably for a lot of modern stuff...
$ fab check

# Localdev server, serving up a local well-known directory on a unix-like system
$ fab run_server
```

... and `fab run_server` is failing for me.

Is there any chance that I can ask for a huge lift on your part to get `fab run_server` running for the demo project so I can jump in and kick the tires again on the project? (I really do apologize that I'm a couple years out of my last python professional work, so need a bit of help, and figure it would be great to get the project in shape to run in a deterministic, reproducible dev scenario again 😉  )

Thanks!

**Comment by ryan-roemer** [comment]
@c-w -- would you mind emailing me at `ryan.roemer@formidable.com` so I can touch base with a few other details to hopefully help make things easier wrt your needs and goals for work on this project? Or twitter DM too works if that's your jam: https://twitter.com/ryan_roemer

**Comment by c-w** [comment]
@ryan-roemer as of 01a5a39 `fab check` and `fab run_server` should work again out of the box (tested on Windows with Python 3.7.3)

**Comment by ryan-roemer** [comment]
@c-w -- Looking great! 🎉 One last thing is when I run `fab run_server` and navigate to http://127.0.0.1:8000/admin/ I get 404s for:

- http://127.0.0.1:8000/admin/admin/css/base.css
- http://127.0.0.1:8000/admin/admin/css/dashboard.css

... etc. If you happen to know how that works now, do you have any ideas for that?

**Comment by c-w** [comment]
@ryan-roemer The static media serving for django-admin should be fixed as of d3e34cc (tested with Django==1.8).

**Pull request merged**
